### ISSUE TITLE
1.19.3 Plugin Crashes Server

### ISSUE THREAD

**Issue by rackgaming** [Pixelated-Studios/SurvivalPlus#34] opened 2023-01-08 03:10 UTC
__**Describe the bug**__
`[04:05:26] [Server thread/ERROR]: Could not load 'plugins/SurvivalPlus-4.0.8-BETA.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: net/kyori/adventure/text/Component
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:149) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.loadPlugins(CraftServer.java:428) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3636-Spigot-d90018e-941d7e9]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:219) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3636-Spigot-d90018e-941d7e9]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:973) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3636-Spigot-d90018e-941d7e9]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:301) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3636-Spigot-d90018e-941d7e9]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: net/kyori/adventure/text/Component
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:67) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: net.kyori.adventure.text.Component
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:67) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        ... 7 more`

__**To Reproduce**__
1. Created whole new worlds
2. started server with viabackwards, viaversion, luckperms

__**Expected behavior**__
For the world to generate and have the plugin working?

__**Running Environment (please complete the following information):**__
 - Server Software: Paper 1.19.3
 - Host MagmaNode
 - Version 4.0.8 BETA

__**Server Info (please complete the following information):**__
 - Amount of Plugins being used: 5

**Comment by VetheonDevelops** [comment] 2023-02-08 19:16
This appears to be a bug with 1.19.3 only

Keep in mind we aren't fully compatible with anything higher than 1.19

We will look into these issues, appears to just be a Java incompat issue. Perhaps building with Java 17 will rectify the issue. But we will see soon.

**Comment by expxx** [comment] 2023-04-19 23:47
Appears to be working fine for me. Though, I don't have the exact same setup as you did. I do have 1.19.3. Just missing the plugins. Let me test with those--

Nope. Even with ViaVersion (rewind & backwards) and LuckPerms, appears to be working fine. (Logs here: https://cdn.tsunamidev.team/personal/logs/nrKE7dPGYhJueiTB.txt)

**Comment by VetheonDevelops** [comment] 2023-04-19 23:57
Unable to reproduce, closing issue

**Closed as completed by VetheonDevelops** 2023-04-19 23:57 UTC
Labels: bug, confirmed
